apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: donator-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: donator.com
    http:
      paths:
      - path: /donator
        pathType: Prefix
        backend:
          service:
            name: donator
            port:
              number: 8080

