apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
        - name: manager
          image: huiji0720/manager
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: redis-ip
              value: '172.30.1.18'
            - name: redis-port
              value: '6379'
            - name: react-ip
              value: '192.168.49.2'
            - name: react-port
              value: '31414'
            - name: rabbit-ip
              value: '192.168.49.2'
            - name: rabbit-port
              value: '30057'
            - name: rabbit-user
              value: 'guest'
            - name: rabbit-pw
              value: 'guest'
              
              
