apiVersion: v1
kind: Service
metadata:
  name: manager
spec:
  type: NodePort
  selector:
    app: manager
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31004


