apiVersion: apps/v1
kind: Deployment
metadata:
  name: anonymous
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anonymous
  template:
    metadata:
      labels:
        app: anonymous
    spec:
      containers:
        - name: anonymous
          image: huiji0720/anonymous
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: redis-ip
              value: '172.30.1.18'
            - name: redis-port
              value: '6379'
            - name: react-ip
              value: '192.168.49.2'
            - name: react-port
              value: '31414'