apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anonymous-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: anonymous.com
    http:
      paths:
      - path: /anonymous
        pathType: Prefix
        backend:
          service:
            name: anonymous
            port:
              number: 8080

