apiVersion: v1
kind: Service
metadata:
  name: anonymous
spec:
  type: NodePort
  selector:
    app: anonymous
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31001

