apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logistic
  template:
    metadata:
      labels:
        app: logistic
    spec:
      containers:
        - name: logistic
          image: huiji0720/logistic
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: rabbit-ip
              value: '172.30.1.18'
            - name: rabbit-port
              value: '5672'
            - name: rabbit-user
              value: 'guest'
            - name: rabbit-pw
              value: 'guest'
            - name: mongo-ip
              value: '172.30.1.18'
            - name: mongo-port
              value: '27017'
            - name: mongo-auth
              value: 'admin'
            - name: mongo-db
              value: 'test'
            - name: mongo-user
              value: 'root'
            - name: mongo-pw
              value: '1234'

