version: '3'
services:
 
  logistic:
    image: logistic
    container_name: logistic
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"                                                                                         
    environment:
      mongo-ip: 172.30.1.18
      mongo-port: 27017
      mongo-auth: admin
      mongo-user: root
      mongo-pw: 1234
      mongo-db: test
      rabbit-ip: 172.30.1.18
      rabbit-port: 5672
      rabbit-user: guest
      rabbit-pw: guest