apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logistic-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: logistic.com
    http:
      paths:
      - path: /logistic
        pathType: Prefix
        backend:
          service:
            name: logistic
            port:
              number: 8081


