apiVersion: v1
kind: Service
metadata:
  name: logistic
spec:
  type: NodePort
  selector:
    app: logistic
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      nodePort: 31005
