create table item(
item_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
item_detail longtext not null,
item_nm varchar(50) not null,
item_sell_status varchar(255),
price integer not null,
reg_time datetime(6),
stock_number integer not null,
update_time datetime(6),
primary key (item_id)
)

    create table member (
       member_id bigint not null GENERATED BY DEFAULT AS IDENTITY,
        reg_time timestamp,
        update_time timestamp,
        created_by varchar(255),
        modified_by varchar(255),
        address varchar(255),
        email varchar(255),
        name varchar(255),
        password varchar(255),
        role varchar(255),
        primary key (member_id)
    )