apiVersion: v1
kind: Service
metadata:
  name: donatee
spec:
  type: NodePort
  selector:
    app: donatee
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31003



