version : "3"
services:
  database:
    container_name: donator-market-db
    image : mysql
    environment:
      MYSQL_DATAABASE: shop_db
      MYSQL_USER: donator
      MYSQL_PASSWORD: donator
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - .:/database/mysql
    ports:
      - "3306:3306"
    restart: always


  application:
    container_name: donator-market-app
    image : openjdk:11-jdk
    ports:
      - "8081:8081"
    volumes:
      - .:/application/donator_market_anonymousUser_jar.jar
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://141.164.38.207:3306/shop?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: donator
      SPRING_DATASOURCE_PASSWORD: donator
    restart: always
